version: '3.8'

services:
  verilator:
    image: verilator/verilator:latest
    volumes:
      - .:/work
      - verilator_cache:/tmp/verilator_cache
    working_dir: /work
    entrypoint: /bin/bash
    command: -c "verilator --binary --trace design.sv testbench.sv --top test && ./obj_dir/Vtest"
    stdin_open: true
    tty: true
    environment:
      - VERILATOR_ROOT=/usr/local/share/verilator

volumes:
  verilator_cache: